ds

diff --git a/Pipeline - 07 When b/Pipeline - 07 When
--- a/Pipeline - 07 When
+++ b/Pipeline - 07 When
@@ -9,8 +9,16 @@ pipeline {
                 catchError(buildResult:'SUCCESS',stageResult:'FAILURE') { 
                     sh 'exit 1' 
                     script {
-                        stageResult = false
-                    }   
+                        try {
+                            echo 'This is STAGE1 execution'
+                                sh 'sleep 5'
+                                sh 'exit 1'
+                        }
+                        catch(Exception e) {
+                            echo 'STAGE1 is FAILED'
+                            stageResult = false
+                        }
+                    }     
                 }    
             }
             
